export const IMAGES = [
    { id: 1, title: 'Trash Tree' },
    { id: 2, title: 'Blue sky' },
    { id: 3, title: 'Girl in water' },
    { id: 4, title: 'White city' },
    { id: 5, title: 'Blur water' },
    { id: 6, title: 'Cool girl' },
    { id: 7, title: 'Beach view' },
    { id: 8, title: 'Bird view' },
    { id: 9, title: 'Small town' },
    { id: 10, title: 'Water dropping' },
    { id: 11, title: 'Water fall' },
    { id: 12, title: 'Cool door' },
    { id: 13, title: 'Testicle' },
    { id: 14, title: 'Fitness girl' },
    { id: 15, title: 'Waves' },
    { id: 16, title: 'Lemon' },
    { id: 17, title: 'Rock climbing' },
    { id: 18, title: "Don' know" },
    { id: 19, title: 'Sky' },
    { id: 20, title: 'Dog' },
    { id: 21, title: 'Sky2' }
];
